languaje: python
python:
  - "3.5"
install:
  - sudo pip install -r requirements.txt
script:
  - sudo apt-get install -y python-logilab-common
  - export FLASK_APP=/home/travis/build/haguilarvalenzuela/backend_vr/flaskr
  - export FLASK_DEBUG=1 
  - pytest